# This script is a 'template' which gets generated by fetch_bookings placed into
# the home assistant python_scripts directory When home assistant runs this within
# the sandbox, it will have access to 'hass' object and can update the attribute.

### BOOKINGS_DATA (Set by fetch_bookings.py)
bookings = []
####

logger.info('Storing', len(bookings), 'bookings...')

hass.services.call('python_script', 'hass_entities', {
    'action': 'set_attributes',
    'entity_id': 'input_button.bookings_data',
    'attributes': {
        'bookings': bookings
    }
})

logger.info('Bookings attribute updated')
output["bookings"] = "Stored " + str(len(bookings)) + " bookings"
