# This script is a 'template' which gets generated by fetch_bookings placed into
# the home assistant python_scripts directory When home assistant runs this within
# the sandbox, it will have access to 'hass' object and can update the attribute.

### BOOKINGS_DATA (Set by fetch_bookings.py)
bookings = []
####

logger.debug('Storing', len(bookings), 'bookings...')

# Get the current state and attributes
entity_id = "input_button.bookings_data"
entity = hass.states.get(entity_id)
state = entity.state
attributes = dict(entity.attributes)

# Update the bookings attribute
attributes["bookings"] = bookings

# Set the new state with updated attributes
hass.states.set(entity_id, state, attributes)

# Log the update
logger.debug('Bookings attribute updated')
output["bookings"] = "Stored " + str(len(bookings)) + " bookings"
