blueprint:
  name: Property Occupancy Trigger
  description: Triggers when a specific property becomes occupied or vacant.
  domain: automation
  input:
    property_id:
      name: Listing ID
      description: The listing_id of the property to monitor.
      selector:
        text:

trigger:
  - platform: state
    entity_id: input_text.bookings
    attribute: occupied

condition:
  - condition: template
    value_template: "{{ input('property_id') in state_attr('input_text.bookings', 'occupied') }}"
